Traceback (most recent call last):
  File "main.py", line 61, in <module>
    loss_collect, val_loss_collect, model = train_model(model, optimizer, criterion, NUM_EPOCHS, train_dataloader, test_dataloader, device, scheduler = None)	
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/train_function.py", line 45, in train_model
    out = model(temp_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/BCI_Project/BCI_MI_Classification/models.py", line 95, in forward
    X_data = self.fc1(X_data)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/zhome/08/3/117881/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA out of memory. Tried to allocate 124.00 MiB (GPU 0; 31.75 GiB total capacity; 29.84 GiB already allocated; 78.00 MiB free; 30.44 GiB reserved in total by PyTorch)
